### ISSUE TITLE
[FEATURE REQUEST] - Apply different filters on Source vs Target environments

### ISSUE THREAD

**Issue by nktnet1** [forcedotcom/SFDX-Data-Move-Utility#935] opened 2024-11-27 08:25 UTC
I want to `UPSERT` a subset of my Event objects from `Production` to `Sandbox`.

The query I'm using is:
```sql
SELECT
    id,
    Start_Date1__c
FROM
    Event__c
WHERE
    CALENDAR_YEAR(Start_Date1__c) >= 2024
```

However, the type of `Start_Date1__c` is `Roll-Up Summary (MIN Block)`.
For context, a parent Event can have many children Blocks, and the Block with the minimum start date becomes the `Start_Date1__c` for the Event.
I am not migrating the Block object to Sandbox. 

This causes an issue with `UPSERT`, as the `WHERE` filter condition will only find Events in `Production`, but not `Sandbox` (i.e. the External ID of `Sandbox` Events are not tracked), thus Events unique by their `externalId` will be inserted multiple times (instead of `UPSERT`, where an `UPDATE` is expected).

I've looked into the [targetRecordsFilter](https://help.sfdmu.com/full-documentation/advanced-features/target-records-filter) option, and I believe what I need might be the inverse of that, e.g. `sourceRecordsFilter`.
Alternatively, perhaps the ability to specify the `sourceQuery` and `targetQuery` separately.

Is there currently a workaround for this? Otherwise, I'll convert this question to a feature request.

Thanks ~

**Comment by hknokh** [comment] 2024-11-27 09:25
Hello,

Thank you for reaching out to me. 
Based on the information you've provided, it appears that this is not a bug related to the Plugin.
For issues of this nature, please consult the SFDMU Help Center documentation at https://help.sfdmu.com/ or check the developer forums.
Additionally, you can review our support policy at https://help.sfdmu.com/full-documentation/additional-information/support_policy to understand the types of issues that fall within the scope of my assistance.
Thank you for your understanding and cooperation.

Regards.

**Comment by nktnet1** [comment] 2024-11-27 10:11
Thanks @hknokh - I think it could be considered a "Bug/Issue" in a sense (or at least not clear/easy to debug), since the `UPSERT` operation will only ever perform `INSERT` due to the filtering condition functioning differently on the Source vs Target environment.

Following the linked [support policy](https://help.sfdmu.com/full-documentation/additional-information/support_policy), I've re-titled the issue to be a Feature Request, with the target being the ability to apply filters differently on the Target vs Source environment. Is this okay?

**Comment by hknokh** [comment] 2024-11-27 10:22
OK, got it. Thanks for the suggestion.

Basically for this moment I do not plan to add any new features to the SFDMU.
However, I’m adding this ticket to my roadmap for review at a later time, but please note there's no guarantee of implementation. I’ll keep you updated on any progress if available.

Regards.

**Comment by nktnet1** [comment] 2024-11-28 06:22
I've made a PR in #936, if you don't mind taking a look.
No rush though, will just be using my own fork.

**Comment by hknokh2** [comment] 2024-11-28 07:02
Thank you for the PR.
I will take a look on it as soon as possible.

**Comment by hknokh** [comment] 2024-11-28 09:26
Hey
I reviewed and merged your PR.
It looks ok after my visual code review without actual testing how it works.
Please confirm that you've also tested it in al live scenario, when the original query string does already contain WHERE clause having multiple conditions with parentheses, and in this case the actual source query is constructed as expected by adding defined extra source filter expression in a correct way.
Thanks.

**Comment by hknokh** [comment] 2024-11-28 12:24
Thank you for the update

**Closed by hknokh** 2024-11-28 12:24 UTC
Labels: feature-request, completed
