### ISSUE TITLE
[BUG]-Execution of the command sfdmu:run has been completed. Exit code 2 (COMMAND_INITIALIZATION_ERROR).le

### ISSUE THREAD

**Issue by jayweera** [forcedotcom/SFDX-Data-Move-Utility#578] opened 2023-03-15 20:15 UTC
SFDMU RUN Error:
[ERROR] Command initialization error: Invalid operation 8 is set for the object Industry_Type__c.
[ERROR] Execution of the command sfdmu:run has been completed. Exit code 2 (COMMAND_INITIALIZATION_ERROR).

I completed inserting data from production org to many sandboxes using my export.json without errors. Suddenly I get this error for any new sandboxes I create. Any one can help me 
Thanks

**Comment by jayweera** [comment] 2023-03-15 20:53
I created a new project in VS Code and the authorise the salesforce org. But I still get the above error

**Comment by hknokh** [comment] 2023-03-16 19:07
Hello,
My  apoligies, but this is not what I can help  you with, it looks like a message coming from the salesforce api, it's not the sfdmu error message.
Need to debug on your side or play with the configuration.

**Comment by jayweera** [comment] 2023-03-17 02:20
Thanks knokh, I managed to get it sorted. I removed the extension and reinstalled.
Now I have another issue when migrating Salesforce Case system object

[ERROR] Error during execution of the command:
Product.Name, Entitlement.Name, Source.Subject, BusinessHours.Name
                                ^
ERROR at Row:1:Column:2414
No such column 'Subject' on entity 'Name'

**Comment by hknokh2** [comment] 2023-03-20 18:13
Hello.
Attach full .log and export.json
Please carefully read our https://help.sfdmu.com/additional-information/support_policy

**Comment by jayweera** [comment] 2023-03-20 23:41
Hi Haim,

Can you please see the log file with export.json as there is an error at the update.

I have attached export.json and log file

Thanks
jay

**Comment by hknokh2** [comment] 2023-03-21 05:50
Hello.
I didn't see the attachments here.
It was filtered out, perhaps you should attach directly in the github not via outlook.
Thx.

**Comment by jayweera** [comment] 2023-03-21 06:25
I am sending those files

[2023-03-21__09_10_19.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11025426/2023-03-21__09_10_19.log)
[ExportJson.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11025440/ExportJson.txt)

**Comment by hknokh2** [comment] 2023-05-01 09:41
Hello,

Sorry for the delay. I have checked this using my own export.json file, which is similar to yours and contains three object sets (upsert, update, delete). However, I was unable to reproduce the issue you mentioned. I am currently using version 4.26.10, which is the latest version.

This is a very strange issue. Could you please try to debug it on your side and let me know what you find? Thank you!

**Comment by hknokh** [comment] 2023-05-05 10:56
Hello,
I hope the issue has been resolved for you. I'm closing it for now. 
Please let me know if you have any further questions or update regarding this issue.
Regards.

**Closed by hknokh** 2023-05-05 10:56 UTC
Labels: bug, non-reproducible

**Comment by gnemethartemis** [comment] 2023-12-05 14:45
I'll add this here, since this is the only relevant hit during a web-search: "Invalid operation 8 is set" error was thrown for me when the *operation* was incorrectly spelled - case mismatch in my case. "upsert" vs "Upsert".
