### ISSUE TITLE
{ContentVersion} The Insert API operation FAILED with message: add a verification on maximum allowed file size (52mb)

### ISSUE THREAD

**Issue by VinodSanubalaDJPR** [forcedotcom/SFDX-Data-Move-Utility#321] opened 2021-06-28 02:47 UTC
**Describe the bug**
[11:32:54.694] [core:ExportFiles] {CombatApplication__c} Processing chunk #15 of 46 items.
[11:33:21.352] {ContentVersion} The Insert API operation has been started using REST API.
[11:33:21.368] [Job# REST:Insert] {ContentVersion} The job has been created. Uploading data ...
[11:34:07.824][ERROR] {ContentVersion} The Insert API operation FAILED with message: ; nested exception is: 
	common.exception.ApiException: Maximum size of request reached. Maximum size of request is 52428800 bytes..

**To Reproduce**
uploading contentVersion and contentNotes

**Expected behavior**

 "pollingIntervalMs": 200,
    "bulkthreshold": 20,
    "apiVersion": "47.0",
	"allOrNone" : true,
		
	
  
    "objects": [
	
     {
          "operation": "Upsert",
          "query": "SELECT ALL FROM CombatApplication__c", 
		  "externalId": "Name",
		"afterAddons" : [
             {
                 "module": "core:ExportFiles",
                 "args" : {
                     "operation" : "Insert"
					 
					 
                 }
             }
         ]
      },

**Comment by hknokh** [comment] 2021-06-28 09:43
Hi, @VinodSanubalaDJPR 
Your request does not appear in a full compliance with our CASE OPENING GUIDELINES, so we have no anough information allowing us to resolve this issue. 
Please, attach all required files and other corresponding details as stated in our guildelines, like **FULL** versions of **export.json, .log files, _target.csv files**, etc (see the repository home page for the list of necessary information should be attached to the case). 
In addition I need to know how large is the total volume of the Files you are trying to upload, what is the total size of them, what is the total size of this specific file that is got failed.
But, I want to notice you in advance, since such cases are not easly reproducable and I am not pretty sure that eventually I will be able to do that on my side, the best and the fastest way is to provide me the access to your test envs  including all necessary details to reproduce and to investigate the issue in a live mode.
Thanks!

**Comment by VinodSanubalaDJPR** [comment] 2021-06-28 12:13
Hi Haim,

Thanks for quick reaponse.

Regarding providing access to test env, I need to check with my manager. however we can have a quick 30 min teams call anytime you suggest.

I am attaching the requested files.

I could uploaded csv, so i had to change it to text files.

[2021-06-28__16_53_24.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6726063/2021-06-28__16_53_24.log)
[json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6726077/json.txt)
[tgt1.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6726118/tgt1.txt)
[tgt2.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6726119/tgt2.txt)


Thanks,
Vinod

**Comment by VinodSanubalaDJPR** [comment] 2021-06-30 02:22
![image](https://user-images.githubusercontent.com/83742605/123892404-dca7a800-d99d-11eb-9e3a-cc8a37de2615.png)

**Comment by VinodSanubalaDJPR** [comment] 2021-06-30 02:23
Would you be able to help with above error

**Comment by hknokh** [comment] 2021-06-30 07:37
Hi Vinod

*******
Regarding the last issue
Check this article:
https://developer.salesforce.com/forums/?id=9060G0000005SluQAE

The reason is it could not make an insert, because the Tool is copying **ALL** ContentDocumentLink data to the Target from the Source **AS IS**. You need to check if he combination of the source **ShareType/Visibility** is compatible with the Target environment.

In addition I see the same error message in the tg1.txt above. Is it the fragment of the same file ?

*******
Regarding  your original  issue of max request size. 

Unfornunatelly it's something coming from the SF API having limit of 52mb on the uploaded contentdocument size and we can't work arround this.

Please found below the article describing about this limitation:
https://docs.copado.com/article/0deqnmjj1v-data-deployment-error-maximum-size-of-request-reached-maximum-size-of-request-is-52428800-bytes

The Tool however internally limits the request contains **MULTPLE** file attachments up to 50Mb to avoid the documented limitation. But when a **SINGLE**  file contains more the 50Mb (as yours) - it tryes to upload it anyway, which indeed causes an error, but it's nothing to do for now with this. We can't migrate so much large file due to native API limitations. 

I will check if I can add an internal validation on the transferred files if the file exceeds the max byte size before uploading.
Since it's not implemented yet, for now - try to manually filter out large files  using query on the Account object having only the smal-size file attachments.

I also will  check regarding an internal maxsize checking.

**Comment by VinodSanubalaDJPR** [comment] 2021-06-30 07:43
Thanks for the response.

As I was gettting max size error, I have limited extract size to 7 records, after that I am getting InternalUser Issue.

Share type and visilibity, of the ContentDocument or the Object itself?

if posible can we have a quick 30 min team meeting, I have been struck with this issue for a while now.

Rgds,
Vinod

**Comment by hknokh** [comment] 2021-06-30 07:56
Unfortunatelly I can't have a call right now. Maybe next week I will be less loaded in my agenda.
Regarding the visibility - this is on ContentDocumentLink, it has 2 properties Visibility and ShareType.
Please check here 
https://help.salesforce.com/articleView?id=000320738&type=1&mode=1
Suppose you need to have AllUsers as a visibility type but not sure. Try to upload only the files having settings of **AllUsers/V** and let me know
If it is working, I also need to check if I can add an option to the Plugin for set the target visibility and sharetype.

**Comment by VinodSanubalaDJPR** [comment] 2021-06-30 08:39
Thanks for response buddy,

Could I lock in for Monday, next week. I will share the team meeting at around this time.

Thanks Heaps.

Vinod

**Comment by hknokh** [comment] 2021-06-30 20:48
Hello @VinodSanubalaDJPR 
Sorry, I have extemelly limited time to support this tool, it is my side project and since I am pretty loaded with my primary job I can not schedule meeting in advance.  Moreover for my opinion the meeting will not be so helpful in our case, since the problem is very clear. For now I would advice you to try playing with the content link sharing as described in the help articles above. When i will have next free time frame, I will also check on my end for adding a new feature of defining custom visibility and sharing when migrating Files. I hope this feature will give more flexibility and will help in such cases as yours.
Sorry again.

**Comment by VinodSanubalaDJPR** [comment] 2021-07-01 13:51
Thanks for helping buddy.

after updating sharing rules, i am getting different error:

![image](https://user-images.githubusercontent.com/83742605/124135416-24761e80-dac7-11eb-9532-63d38c4e66a6.png)

**Comment by hknokh** [comment] 2021-07-04 13:15
Hello @VinodSanubalaDJPR 
Noway) The only is to give me the access to you test environments to see what is happening myself. 
Please check this with your manager.

**Comment by VinodSanubalaDJPR** [comment] 2021-07-04 13:38
Hi Haim,

Unfortunately, as it's being a sensitive customer data, I won't be able to give access, however we can have a call whenever you have 15 min.

If you work with salesforce I can open a case and assign it to you.

Please help me here I have been struggling with this issue for a while now.

Thanks,
Vinod

Get Outlook for Androi<https://aka.ms/AAb9ysg>

________________________________

**Comment by hknokh** [comment] 2021-07-04 18:23
Ok. @VinodSanubalaDJPR 
I will check regarding the call.
Let me know please your email address I can schedule a meeting in the Google Meet.

**Comment by VinodSanubalaDJPR** [comment] 2021-07-05 02:28
Hi Haim,

Thanks for going to take time for fixing the issue.

My id is :  ***@***.******@***.***>

Cant thank enough.

Regards,
Vinod

**Comment by hknokh** [comment] 2021-07-05 05:42
Didn't see the email. Possible it's hidden by the github.
Please post it directly to haim.knokh@gmail.com

**Comment by VinodSanubalaDJPR** [comment] 2021-07-05 06:21
Hi Haim,

Please find my email Id, can reach me any time.

***@***.******@***.***> or ***@***.******@***.***>

Thanks,
Vinod

**Comment by hknokh** [comment] 2021-07-11 08:42
Hello @VinodSanubalaDJPR 
I was trying to reach out  you once, but you wasn't available then.
I'm closing this issue for the current moment. Reopen, if you need an additional help.
As you can't provide me access to your environment due to security reasons, please try to clone the plugin repo locally and to debug it yourself (as described here:  https://help.sfdmu.com/plugin-basics/basic-usage/debugging) and let me know if you see something.
Thank you!

**Closed by hknokh** 2021-07-11 08:42 UTC
Labels: KB, New feature, help wanted
