### ISSUE TITLE
I am working on this version v3.1.16 previously it is working for me

### ISSUE THREAD

**Issue by SFDMUTOOL** [forcedotcom/SFDX-Data-Move-Utility#690] opened 2024-02-25 17:36 UTC
**Describe the bug**
Previously I am working on this v 3.1.16 and it's working as expected.  Data is migrated from one org to another  org. 

**To Reproduce**
When I am running the script I am getting the error message : 
**sfdx sfdmu:run --sourceusername galaxyUat --targetusername Dev2GalaxyOrg --path C:\Users\gnavula\Documents\SFDMU_APP\data\gourav-navula-amadeus-com\data-anaminzation\ --verbose
» Warning: sfdmu run is not a sf command.
Did you mean apex run? [y/n]:
» Error: Run sf help for a list of available commands.

Executing finished with code 127
I am checking the logs but don't get any thing.
**Expected behavior**
The script needs to  be execute and provide the desired results.
[export1.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14397203/export1.json)

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by SFDMUTOOL** [comment] 2024-03-01 07:53
Hey Team , 

When  I am running the script from the GUI I am getting the below error message : 
PS C:\Users\gnavula\salesforcedatamove\SFDX-Data-Move-Utility-Desktop-App> sfdx sfdmu:run --sourceusername galaxyUat --targetusername Dev2GalaxyOrg --path C:\Users\gnavula\Documents\SFDMU_APP\data\gourav-navula-amadeus-com\data-anaminzation\ --verbose   
 »   Warning: sfdmu run is not a sf command.
Did you mean apex run? [y/n]: Terminate batch job (Y/N)?

**Comment by SFDMUTOOL** [comment] 2024-03-02 17:16
Hey @hknokh,

I am waiting for your reply I have already given the demo to my clients with previous version. Theyall are happy but all of sudden everything is not working . I have to give again demo to them . How can I solve this issue please help me out. 
Regards
Gourav Narula

**Comment by SFDMUTOOL** [comment] 2024-03-02 17:26
Hey @hknokh , 

I have cloned the new version also  but the UI of the new version is very clumsy as compared to pervious UI. I am not able select the object fields and not able to  do the query. If there is any expectation date when we get the better UI. The same UI which  I am using on the previous version. 
![NewVersion](https://github.com/forcedotcom/SFDX-Data-Move-Utility/assets/161153675/a41b2610-9661-454b-b4f2-dc2ba44a78f8)
Regards
Gourav

**Comment by hknokh2** [comment] 2024-03-02 19:23
Hello,

Regarding the warning rectangle, there is an issue with the fields you have selected. Please hover your mouse over the rectangle to view the message. It is necessary to address all errors in the configuration before proceeding.

Additionally, you can use the blue arrow to collapse the left pane, which contains the steps wizard. This action will expand the main pane, allowing you to view the field selector in a wider format.

This is the latest version and includes the most recent SFDMU features. Currently, there are no plans to develop another GUI in the future. The aim is to familiarize yourself with its operation, which will enhance your user experience.

Best regards.

**Comment by hknokh2** [comment] 2024-03-02 19:33
Additionally, the new version supports the latest SF CLI, which is configured via the export.json file. Please refer to the documentation for details. The older version does not support this and only works with the outdated SFDX CLI. If you wish to revert to the old UI, you can download and use any previous version from the list of previous releases published in the GitHub repository.

**Comment by hknokh** [comment] 2024-03-03 01:03
I've resolved some issues with running SFDMU on the latest SF CLI platform. Please update the GUI and Plugin accordingly. Additionally, the error message "sfdmu run is not a sf command" might be caused by a corrupted installation of the SFDMU plugin. You can address this by reinstalling the SFDMU plugin.

**Comment by hknokh** [comment] 2024-03-10 21:34
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.

**Closed by hknokh** 2024-03-10 21:34 UTC
Labels: help-wanted, completed, kb-important, to-be-closed
