### ISSUE TITLE
[ISSUE] - Failed to upsert Contact

### ISSUE THREAD

**Issue by ilanhazan** [forcedotcom/SFDX-Data-Move-Utility#47] opened 2020-05-26 16:07 UTC
Hello,
When running the command for the first time it succeed.
Running it the second time we expect that the program will recognize that the emails are exist hence doing nothing.
However it produce errors in the target:
"You cannot create a duplicate Contact, Email already exists!"

The export is:
  {
            "operation": "Upsert",
            "externalId": "Email",
            "query": "SELECT Id, Name,Email,Platform_Role__c,LastName,FirstName,Salutation,Secondary_Email__c,MailingCity FROM Contact Where .....",
            "allRecords": false
        }

**Comment by hknokh** [comment] 2020-05-26 20:30
@ilanhazan 
I tried your configuration for the transferring only Contacts without accounts with the same query - any time it works as expected on upsert.  And it  also gives me warning about records no need to be updated. So could not reproduce your issue.

Today I improved the plugin with adding the info message on upsert/update when the target records not need update, like below:

"=== UPDATING THE TARGET STEP 1...
[2020-05-26 23:19:40.857] {Contact} [INFO] There are 2 skipped updates, since the records have no difference between the Source and the Target.
[2020-05-26 23:19:40.858] Nothing was updated
"
+ some small fixes

Please, update the plugin to the latest version (2.8.341) and try to migrate Contacts again.
Hope the upsert will now work for you.

**Closed** 2020-05-27 20:15 UTC
Labels: bug, completed
