### ISSUE TITLE
[QUESTION] - Deprecated config name: apiVersion

### ISSUE THREAD

**Issue by EbieGit** [forcedotcom/SFDX-Data-Move-Utility#877] opened 2024-09-09 11:52 UTC
Command line gives a warning about deprecated config name apiVersion and suggests to use org-api-version instead.
The GUI seems to use apiVersion instead of org-api-version

![apiVersion-Warning](https://github.com/user-attachments/assets/744b4458-eddb-45d5-b428-70edce13abfe)

![apiVersion](https://github.com/user-attachments/assets/daf089d6-6dbc-4a04-b448-ac4d1e6a8fd7)

**Comment by hknokh** [comment] 2024-09-09 12:06
Hello, @EbieGit

Thank you for reaching out.
I will do my best to assist you as quickly as possible and will keep you updated on my progress.

Cheers

**Comment by hknokh2** [comment] 2024-09-09 14:26
The issue is not caused by adding an incorrect `--apiVersion` flag to your CLI string. Instead, it's due to incompatibility between the plugin code and the latest SF-CLI API. However, there's no need to worry as it won't critically affect the data migration. 

If you'd like to change the running API version, avoid using the CLI flag; instead, set this property:  
[apiVersion property](https://help.sfdmu.com/full-documentation/export-json-file-objects-specification/script-object#apiversion-string-in-float-format).

I've change this issue to a feature request for a future review.

**Comment by hknokh** [comment] 2024-09-09 14:30
I am closing this issue for now. I will review the feature request at a later time. I will provide further updates if there are any developments.

Best regards.

**Closed by hknokh** 2024-09-09 14:30 UTC
Labels: help-wanted, completed
