### ISSUE TITLE
[QUESTION] - Attachment Migration - Parent Relationship Configuration

### ISSUE THREAD

**Issue by andreyzh** [forcedotcom/SFDX-Data-Move-Utility#354] opened 2021-10-15 07:34 UTC
Good day! I am trying to set up a job to migrate certain kind of Cases which have related Email Messages which have related Attachments. The source org is a very old with Classic UI, destination org is relatively fresh with Lightning UI in use.  

My problem is the following error message:   
__[ERROR] Error during execution of the command: TYPEOF operand 'Parent' and top-level SELECT list element 'Parent.Name' may not reference the same relationship field.
Execution of the command sfdmu:run has been finished. Exit code 4 (COMMAND_EXECUTION_ERROR).__  

From what I can see this comes from the Attachment object.

I tried different combinations of the query for Attachments, but none seems to work as expected.  
Any advice on the correct configuration is very appreciated!  
Attached are export.json and log.  

[2021-10-15__10_22_15.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7351688/2021-10-15__10_22_15.log)
   
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7351704/export.txt)

Export.json for quick reference.  
![image](https://user-images.githubusercontent.com/6769562/137450089-47aae880-d679-43f7-be4a-ccccb825ac66.png)

**Comment by hknokh** [comment] 2021-10-19 19:52
Hello @andreyzh 

I found some issues in the export.json you provided me.

This is the configuraiton which is working for me:

{
    "bulkThreshhold": 200,
    "objects": [
        {
            "query": "SELECT Id, Subject, Description FROM Case WHERE Case_Country__c = 'Switzerland'",
            "operation": "Insert",
            "master": true
        },
        {
            "query": "SELECT Id, Status, ParentId, FromAddress, FromName, Subject, HtmlBody FROM EmailMessage",
            "operation": "Insert",
            "master": false
        },
        {
            "query": "SELECT Id, Body, ContentType, Description, Name, ParentId$EmailMessage FROM Attachment WHERE Parent.Type = 'EmailMessage'",
            "operation": "Insert",
            "master": false
        }
    ]
}

1. you've missed comma between the fields:  **ParentId$Case FromAddress**
2. all the fields in queries should be in a right case (f.ex **F**romAddress instead of **f**romAddress)
3. the  ParentId of Email message is **not** a polymorphic field, it always references Cases, so the expression ParentId$Case is not correct in this context

I've also applied some fixes, please update the Plugin to the latest version and retry with my export.json instead of yours.

**Comment by hknokh** [comment] 2021-10-20 08:24
Hello
The same config which I attached is working fine on my end.
You can give me access to you orgs in order to check int on your end.

**Comment by andreyzh** [comment] 2021-10-20 08:51
I used the exact same export.json as you have provided now - same problem. From what I can see the Parent.Subject might be an issue due to the polymorphic nature of Attachment.ParentId - according to docs it can point to an array of objects.  

I can't provide access to the org because it's a customer's instance. Not even sure I can given an example of such org e.g. Trailhead or DevOrg as there is quite a bit of legacy :)  

Would there be any other option, e.g. Google Meet / screen share if you happen to have time?

**Comment by hknokh** [comment] 2021-10-20 09:18
Understand.
Not sure about the meeting.
Try to run the following query in your org if it's working.
**SELECT Id, Body, ContentType, Description, Name, ParentId, TYPEOF Parent WHEN EmailMessage THEN Id END, TYPEOF Parent WHEN EmailMessage THEN Subject END FROM Attachment WHERE Parent.Type = 'EmailMessage'**
This query is actually running under the hood
The legacy orgs might not support some SOQL features, think it's the issue.
If not you should clone the repo and debug yourself because I can't reproduce.

**Comment by andreyzh** [comment] 2021-10-20 09:53
That query worked indeed. I've never seen such syntax in SOQL before, learned something new today, thanks!
![image](https://user-images.githubusercontent.com/6769562/138069347-ef9c1c88-785e-44e1-8efa-7c861470c47d.png)

By the way - it looks like we work in one company. I found you in Slack, pinged some time ago, but I'm not sure if the message went though :)

**Comment by hknokh** [comment] 2021-10-20 10:52
I'm closing this ticket since we have recently solved the issue.
Feel free to reach out if any  additional help needed.

**Closed by hknokh** 2021-10-20 10:52 UTC
Labels: help wanted
