### ISSUE TITLE
[BUG] - malformed Composite External ID field causes Extraneous input error

### ISSUE THREAD

**Issue by readeral** [forcedotcom/SFDX-Data-Move-Utility#879] opened 2024-09-11 01:02 UTC
**Describe the bug**
```
Error during execution of the command: line 1:932 extraneous input 'FROM' expecting {GROUP, ABOVE...}.
Execution of the command sfdmu:run has been completed. Exit code 4 (COMMAND_EXECUTION_ERROR).
```

When a Composite External ID field has a trailing semicolon (as often auto completed by IDE), sfdmu:run fails with the above (truncated) error. The issue is a potential misdirection as the problematic object's query utilises `FROM`, making it hard to realise the extraneous input is in the `externalId` field.

**To Reproduce**
Provide a malformed externalId with a trailing semicolon:
```
{
   "label": "contact",
   "operation": "Upsert",
   "externalId": "Name;Email;",
   "query": "SELECT Id, AccountId, LastName, FirstName, Email FROM Contact",
}
```

**Expected behavior**
Error reports a malformed externalID OR sfdmu:run strips trailing semi-colons from externalID fields

**export.json**
[export.json](https://github.com/user-attachments/files/16956449/export.json)

**Log file**
[2024-09-11__10_51_02.log](https://github.com/user-attachments/files/16956442/2024-09-11__10_51_02.log)

**Comment by readeral** [comment] 2024-09-11 01:12
(Don't mind my label key, that's just my solution to not having comments in JSON so I don't have to scroll to the end of the query to see what the object is - SFDMU happily ignores the unrecognised key)

**Comment by hknokh** [comment] 2024-09-11 01:18
Hello, @readeral

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by readeral** [comment] 2024-09-14 04:03
Bump

**Comment by readeral** [comment] 2024-09-15 04:09
@hknokh we can move testing discussion here

**Comment by hknokh2** [comment] 2024-09-15 04:15
Np. But not sure that I can add something to what I already said.

**Comment by readeral** [comment] 2024-09-15 04:32
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues/881#issuecomment-2351350575
> There is no specific standard for this project beyond the common standards that apply to all development. If you're not sure, it's best not to make a contribution.

@hknokh This isn't particularly satisfying. Do you want a contributor to test every function? That would be a common standard for many projects, because they have unit tests for every function. Many other open-source projects have no testing, you could call that a 'common standard' given how common it actually is.

Maybe a first step would be to commit your regression tests to the repo. We can match your testing methodology before committing. That would boost some confidence.

The contribution I want to make is to strip the trailing semicolon from the externalId field. It would be a minor/cosmetic contribution, just a minor help with usability, not introducing new functionality, but writing a suite of tests for all 105 references to externalId is a remarkable amount of work to do from scratch.

**Comment by hknokh2** [comment] 2024-09-15 04:53
This project does not have unit tests because they are not needed and won't catch any errors. Testing should only be done in a real data migration job, which I run in debug mode and test every line of code which can cause issues. I have a couple of test jobs that cover common cases for regressions. And also I know what I do.

I don't expect contributors to test every function. Instead, they should test the job that can verify their changes.

Regarding the semicolon, please create a PR and ensure it generates the correct export.json with the proper externalId, indicating that you've fixed the error. However, please don't assume your PR will be accepted if the change differs from the overall code style of this application or isn't an efficient solution. This is the purpose of the code review process. 
And I am not sure that the semicolon is so small change. You should properly fix the autocomplete functionality. But let's see your solution. Also, please keep in mind that I don't create release in every change, so at the beginning your change will be available as a source code in the main branch.

**Comment by readeral** [comment] 2024-09-15 05:02
> This project does not have unit tests because they are not needed and won't catch any errors. Testing should only be done in a real data migration job, which I run in debug mode and test every line of code which can cause issues. I have a couple of test jobs that cover common cases for regressions. And also I know what I do.
> 
> I don't expect contributors to test every function. Instead, they should test the job that can verify their changes.
> 
> Regarding the semicolon, please create a PR and ensure it generates the correct export.json with the proper externalId, indicating that you've fixed the error. However, please don't assume your PR will be accepted if the change differs from the overall code style of this application or isn't an efficient solution. This is the purpose of the code review process. And I am not sure that the semicolon is so small change. You should properly fix the autocomplete functionality. But let's see your solution. Also, please keep in mind that I don't create release in every change, so at the beginning your change will be available as a source code in the main branch.

I don't see it as a small change either, as I say, plenty of places for it to go wrong, but it fits within your definition of allowed contributions.

The autocompletion is a perfectly reasonable thing for my IDE to infer is needed, it would be wild for me to make a rule that is specific to export.json. What would be better is for your code to parse complex externalIds to ensure they are of an appropriate format to be consumed, and if not, to throw an error to identify the malformed externalId instead of letting the exception bubble up to the SF CLI error.

Contributing that much code _would_ be problematic, so maybe I'll just leave that up to you. I don't want to risk deviating from your preferred code style.

**Comment by hknokh2** [comment] 2024-09-15 05:04
Of course, I will fix it. But now I have no enough time. I will update you once it will done.

**Comment by hknokh2** [comment] 2024-09-18 22:19
@readeral  
I updated the [Code Contribution Policy](https://help.sfdmu.com/additional-information/code_contribution_policy) and [Support Policy](https://help.sfdmu.com/additional-information/support_policy) to better highlight what we've previously discussed.

**Comment by hknokh** [comment] 2024-09-19 15:05
@readeral, 
I've resolved this issue. However, the fix will be included in the next app release, along with other improvements. Please keep an eye on the repository updates.
I'll close this issue for now, marking it as "waiting for release."
Regards.

**Closed by hknokh** 2024-09-19 15:05 UTC
Labels: bug, completed
