### ISSUE TITLE
[QUESTION] - Attachments not being paired with EmailMessage records 

### ISSUE THREAD

**Issue by samarmstrong111** [forcedotcom/SFDX-Data-Move-Utility#669] opened 2023-12-04 11:35 UTC
- Ask your question or what kind of help you need.
I'm trying to migrate Attachment records with EmailMessages for an org migration, and have already moved over EmailMessage records. 
When trying to migrate the Attachments I'm finding it's not setting the ParentId field when trying to upload. I've narrowed down the criteria to try with just one record so far just to try a bunch of different configurations.
Legacy_Id__c is an externalId field on the target org, and to avoid errors I've created this field on current production with CASESAFEID(Id). 

It tells me that the EmailMessage migration doesn't need to happen because nothing is different, but then doesn't populate the ParentId when trying to insert Attachments.

[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13545376/export.json)
[MissingParentRecordsReport.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13545377/MissingParentRecordsReport.csv)
[Attachment_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13545378/Attachment_insert_target.csv)
[2023-12-04__11_18_17.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/13545423/2023-12-04__11_18_17.log)

There's no EmailMessage target because it matched between the new orgs and said there were no changes between the two, but that would just be Id, Legacy_Id__c with the same values as in the queries.

**Comment by hknokh2** [comment] 2023-12-04 20:31
Hello,
Thank you for reaching out to me. 
I will take a look at your case and let you know if there are any updates.
Cheers.

**Comment by samarmstrong111** [comment] 2023-12-05 11:42
Awesome, thank you very much. This tool's been excellent so far, I've been able to migrate pretty much our entire production environment, and all that's left are the various types of files, which so far has been much less painful than I can imagine going through the normal exporting and relinking would be for the amount of data we have.

**Comment by hknokh2** [comment] 2023-12-11 22:40
I've managed to reproduce the issue. Now, I need to examine how it functions when the Field Mapping feature is applied to a parent object that is set to read-only. I observed that the attachment transfers successfully when a new Email Message record is created, but not when it's in read-only mode.

**Comment by hknokh2** [comment] 2024-03-10 01:16
Hello,

Upon further review of your case, I noticed issues with your `export.json` configuration:

1. **External ID Field Mapping:** When a field mapped is also designated as an external ID, the source field, not the target, should be marked as the external ID. For instance, in the `EmailMessage` mapping where `Id` is mapped to `Legacy_Id__c`, `Id` should be set as the external ID for `EmailMessage`, rather than `Legacy_Id__c`.

2. **Use of `Id` Field:** It's not possible to map the `Id` field and use it as an external ID simultaneously. Instead, consider using another field. For example, mapping `Subject` to `Legacy_Id__c` and using `Subject` as the external ID should work effectively.

Due to the current setup, the plugin will only be able to insert new email messages but will fail to recognize existing ones. This means it won't find matching records in the target org for operations like Readonly or Update, leading to missing `ParentId` for `EmailMessage` attachments.

Best regards.

**Comment by hknokh** [comment] 2024-03-10 23:42
Hello.

I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.

Regards.

**Closed by hknokh** 2024-03-10 23:42 UTC
Labels: help-wanted, completed
