### ISSUE TITLE
[BUG] - [WARN] Can not load module C:\MySfdmuAddOns\CustomSfdmuRunAddonTemplate.

### ISSUE THREAD

**Issue by fsi-hiraisht** [forcedotcom/SFDX-Data-Move-Utility#600] opened 2023-06-08 01:39 UTC
**question**
I specified the addon module template (CustomSfdmuRunAddonTemplate) described in the SFDMU help page as the "path" in export.json and ran SFDMU, but a warning was displayed and the addon module could not be loaded.
The target record was updated in the data migration destination organization, but the content of the add-on module template could not change the field value.
How do I configure it so that it can load addon modules?

**Reproduce**
Run the migration job using the attached export.json.

**Template used**
https://help.sfdmu.com/full-documentation/add-on-api/custom-sfdmu-add-on-api
・CustomSfdmuRunAddonTemplate
→ As described, "npm run build" was executed, and the generated "CustomSfdmuRunAddonTemplate" and "package" folders were copied under C:\MySfdmuAddOns.

**expected behavior**
No warning, TEST1__c and TEST__c values are updated in the data migration destination organization as per the add-on module template contents.

**Full .log file.**
[2023-06-02__10_59_06.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11683094/2023-06-02__10_59_06.log)
(Only the organization name is anonymized)

**Full export.json file.**
export.json
```
{
    "objects": [
        {
            "operation": "Upsert",
            "externalId": "Name",
            "deleteOldData" : true,
            "query": "SELECT Id, Name, LongText__c, TEST__c, TEST1__c  FROM Account WHERE Name = 'ACC_10000'",
            "beforeUpdateAddons" : [
                {
                        "description": "This example of the Sustom SFDMU AddOn module manipulates with the source Account records right before the target SF object going to be updated. It extracts the value from the JSON stored in the LongText__c, then puts the extracted string into the TEST1__c.",
                        "path" : "C:\\MySfdmuAddOns\\CustomSfdmuRunAddonTemplate",
                        "args" : {
                            "TEST__c": "Another small manipulation with the source data: we want to populate the TEST__c field of each record with this constant text."
                        }
                }
            ]
        }
    ]
}
```

**_target.csv file**
[Account_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/11683112/Account_insert_target.csv)

**Comment by hknokh2** [comment] 2023-06-08 09:20
Hello,
Thank you for reaching out to me. 
I'm checking this issue on my side.
Cheers.

**Comment by hknokh** [comment] 2023-06-12 07:24
All is ok. It's a bot.
I'm putting this case to 'in progress' to prevent autoclose.

**Comment by hknokh2** [comment] 2023-06-25 16:00
Hello,
The issue has been resolved. To apply the fix, please update the SFDMU source code. Once updated, recompile the code and proceed with repeating the remaining steps to run the demo custom Add-On.
If you have any further questions or need additional assistance, please don't hesitate to ask.
Regards.

**Comment by fsi-hiraisht** [comment] 2023-06-27 04:44
Hello,
I have also verified that the demo custom add-on works as expected.
Thank you for your response.

**Comment by hknokh** [comment] 2023-06-27 09:13
This case has been closed as the issue is resolved.
Regards.

**Closed by hknokh** 2023-06-27 09:13 UTC
Labels: bug, completed
