### ISSUE TITLE
[BUG]- Cannot find module './sfdmuRunPluginTask'

### ISSUE THREAD

**Issue by ozanbotanls** [forcedotcom/SFDX-Data-Move-Utility#271] opened 2021-02-25 16:48 UTC
**Describe the bug**

When I run `sfdmu:run` command in my CI server, started to get this. I believe this is with the latest version as in my local machine I have version 3.7.21 installed and have no issues.

```
Error: Cannot find module './sfdmuRunPluginTask'
    Require stack:
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/addons/engine/sfdm
    u-run/sfdmuRunPluginJob.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/addons/engine/sfdm
    u-run/sfdmuRunPluginRuntime.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/addons/engine/addo
    nManager.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/scr
    ipt_models/script.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/modules/models/ind
    ex.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/modules/components
    /common_components/common.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/modules/components
    /common_components/logger.js
    - /github/home/.local/share/sfdx/node_modules/sfdmu/lib/commands/sfdmu/run
    .js
    - /usr/local/lib/sfdx/node_modules/@oclif/config/lib/plugin.js
    - /usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js
    - /usr/local/lib/sfdx/node_modules/@oclif/config/lib/index.js
    - /usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js
    - /usr/local/lib/sfdx/node_modules/@oclif/command/lib/index.js
    - /usr/local/lib/sfdx/dist/cli.js
    - /usr/local/lib/sfdx/bin/sfdx.js
```

**To Reproduce**

sfdx sfdmu:run

**Expected behavior**

The plugin should work as expected.

**Comment by ozanbotanls** [comment] 2021-02-25 16:51
@hknokh 
The problem should be here: https://github.com/forcedotcom/SFDX-Data-Move-Utility/blob/1ec076034c2e7fe8741cdeef0bf7dc154514d389/src/addons/engine/sfdmu-run/sfdmuRunPluginJob.ts#L13

The file name starts with a capital in the parent folder.

**Comment by hknokh** [comment] 2021-02-25 19:40
Hello @ozanbotanls 
Right now uploaded fix for this. It was filename misspelling (first capital letter).
Please reinstall to 3.10.2, don't use outdated version because each version has fixes and you can suddenly have unexpected issues with old versions. )
Thanks.

**Comment by ozanbotanls** [comment] 2021-02-25 20:36
Hey @hknokh 
No still getting the same issue with the new version.

**Comment by ozanbotanls** [comment] 2021-02-25 20:45
What I'm saying is you have your file name starting with capital and you try to import it with lowercase - can you make sure this is not causing the issue?

![Screen Shot 2021-02-25 at 3 44 24 PM](https://user-images.githubusercontent.com/57642636/109214902-66d9c880-7780-11eb-8f42-c96709a26df4.png)

**Comment by hknokh** [comment] 2021-02-25 21:14
I fixed the filename

**Comment by hknokh** [comment] 2021-02-25 21:15
try sfdx plugins:uninstall sfdmu
then sfdx plugins:install sfdmu

**Comment by hknokh** [comment] 2021-02-25 21:20
![12345](https://user-images.githubusercontent.com/15181301/109219252-09656c00-77c0-11eb-833a-fb9205d476b9.jpg)

**Comment by hknokh** [comment] 2021-02-25 21:23
![88888](https://user-images.githubusercontent.com/15181301/109219529-63663180-77c0-11eb-9fca-72580c1152b8.jpg)

**Comment by hknokh** [comment] 2021-02-25 21:34
I understand what you say. But the file should start with lowcase letter. I fixed the filename, see the screenshot, try to reinstall.

**Comment by azlam-abdulsalam** [comment] 2021-02-28 09:55
@hknokh tried uninstalling and installing, it didn't work

**Comment by hknokh** [comment] 2021-02-28 12:26
Ok, weird, dont know what to say, maybe cached lib content with wrong js filename while compiling and publishing the plugin to the npm on my pc.  I will check this point again and will update you asap. I can not reproduce it neither on mac os now on windows while installing it from npm.

**Comment by azlam-abdulsalam** [comment] 2021-02-28 12:39
I have had similar issues in my project,can be reproduced in a docker or CI scenario

**Comment by hknokh** [comment] 2021-02-28 12:45
Ok, it is not reproducable for me. I will update you when have news, for now use any worked version.

**Comment by hknokh** [comment] 2021-02-28 19:18
@azlam-abdulsalam @ozanbotanls 
I guess, I found the problem, as I said the compile directory was containing incorrect cached file with the first capital letter.
Can you try to reinstall if it's solved ?
Thx

**Comment by ozanbotanls** [comment] 2021-02-28 20:42
@hknokh Yes, it is fine now on my CI server.

**Closed** 2021-02-28 21:12 UTC
Labels: bug
