### ISSUE TITLE
[BUG]-Standard Product field treated as a lookup when while it's a text field

### ISSUE THREAD

**Issue by Kirill-H** [forcedotcom/SFDX-Data-Move-Utility#309] opened 2021-05-18 04:20 UTC
**Describe the bug**
When moving the standard Product2 object - if the ExternalId standard field is included in the query - the script fails saying it can't recognize the lookup relationship. This is actually a text field but as it end with Id, I assume you treat it as other standard lookup fields.

**To Reproduce**
Migrate the Product2 object with all editable fields.

**Expected behavior**
Product2 data to be moved to the specified sandbox.

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment] 2021-05-18 05:48
Hi @Kirill-H 
I would ask you to always follow the case opening guidelines. It's important for the case resolving.
The cases which is incompatible will not be treated.
However regarding this ticket, I can understand the root case of this. I will check.

**Comment by hknokh** [comment] 2021-05-23 03:03
Hello @Kirill-H 
Can't reproduce.
Just tried to migrate product2 with the newest version 4.4.0 and it was migrated without issues
Following the config I used:
{
    "objects": [
        {
            "operation": "Upsert",
            "externalId": "ProductCode",
            "query": "SELECT **ExternalId**, Id, IsActive, Name, ProductCode FROM Product2"
        }
    ]
}
Please recheck.

**Comment by hknokh** [comment] 2021-05-23 03:53
***
This case is closed since the issue is not reproducable with the provided information.
If you have any additional information to give to us, feel free to reopen the case.

**Comment by Kirill-H** [comment] 2021-05-24 23:08
Cheers for checking @hknokh!
I've just updated the version and ran again - this time encountered an issue with another standard field for a similar reason I suspect. Product2 field API name: ExternalDataSourceId

**Comment by hknokh** [comment] 2021-05-25 05:05
@Kirill-H 
ExternalDataSourceId is lookup field to ExternalDataSource
In general the issue what you say, that Id at the end is ALWAYS treated as lookup - it is not correct. 
The Tool always detects the type of the field from the object metadata, does not make senece the api name of it.

**Closed** 2021-05-25 05:06 UTC
Labels: bug
