### ISSUE TITLE
[BUG]-Incomplete CSV file when pulling a huge amount of data

### ISSUE THREAD

**Issue by R0Wi** [forcedotcom/SFDX-Data-Move-Utility#618] opened 2023-07-31 15:21 UTC
**Describe the bug**

We're using `sfdmu` to download ~100k `Product2` records into a CSV file. We're using an `export.json` like this:

```json
{
	"objects": [
	{
            "query": "SELECT Id, readonly_false FROM Product2",
	    "operation": "Upsert",
            "externalId": "MY_ExternalId__c"
        }
    ]
}
```

We execute the download via `sf sfdmu:run --usesf --sourceusername <USER>--targetusername csvfile`. 

When using `sfdmu` version  `4.29.3`, this worked quite well and all products are downloaded correctly and stored in the CSV file. We recently updated to `4.29.5` and the file now contains only a few hundred lines. But the `sf` command still runs to the end without an error.

**To Reproduce**

1. Setup the `export.json` like described above
2. Execute the CSV download
3. Compare the results of SFDMU versons `4.29.3` and `4.29.5`

**Expected behavior**

Both versions should create the same CSV file content.

**Log file**

Relevant: in both log files one can see that all `Product2` records are received from Salesforce, but obviously in version `4.29.5` they are not written correctly to the CSV file:

```
=== Data retrieval summary.
[12:34:21.381] {Product2} The total amount of the retrieved records: 103437/0.
```

**⚠️ Suspicion**

I have the suspicion that https://github.com/forcedotcom/SFDX-Data-Move-Utility/commit/54284b59d3544960eae47c31cf719f726fe8cfd3 introduces this behaviour.

**Comment by hknokh2** [comment] 2023-07-31 16:06
Hello,
Thank you for informing me about the issue.
I have reverted the suspicious PR back to its original state.
Could you please test it and let me know if the issue is resolved?
Thanks again.

**Comment by R0Wi** [comment] 2023-08-01 06:26
Thanks for your fast feedback @hknokh! Can confirm that with version `4.29.6` everything works again like expected. Didn't manage to dig deeper into the code since I wasn't yet able to run SFDMU directly from source. Are there any docs related to this? Maybe I could give you some more in depth feedback then.

**Comment by hknokh2** [comment] 2023-08-01 08:23
Hello

Thank you for running the tests, and I'm glad to hear that everything is alright now. The broken PR in question was submitted by one of the contributors. Unfortunately, I didn't test it myself and relied on their tests. It seems that the code requires additional debugging. The purpose of the PR is to address the issue of loading very large CSV files using stream transformation. If you could take a look at the desired PR on GitHub and help debug the code, I would greatly appreciate it. At the moment, I'm unable to perform these tests myself. Once again, thank you for your assistance.

Best regards.

**Comment by R0Wi** [comment] 2023-08-01 08:28
Sure would be glad to help! Since I can reproduce the error in my local setup, it would make sense for me to debug the code there. Is there any documentation on how to debug the SFDMU JS code with VSCode or any other IDE?

**Comment by hknokh2** [comment] 2023-08-01 09:04
Thank you for your message.
I hope this article can help.

https://help.sfdmu.com/debugging

**Comment by hknokh** [comment] 2023-08-03 12:48
Hello,
I hope the issue has been resolved for you. I'm closing it for now. Please let me know if you have any further questions.
Regards.

**Closed by hknokh** 2023-08-03 12:48 UTC
Labels: bug, completed
