### ISSUE TITLE
[QUESTION]-Execution ends with no error when querying Group

### ISSUE THREAD

**Issue by ddarmond** [forcedotcom/SFDX-Data-Move-Utility#522] opened 2022-11-11 16:18 UTC
**Describe the bug**
When running the plugin against a large org of >450k users and >1.2mil groups, the job ends after logging 1000001 records.

**To Reproduce**
1. Ensure the source org has >1mil groups.
2. Add a query to the config that references a User lookup field.
3. Run the plugin command

**Expected behavior**
1. The plugin should run to completion successfully, and query and load appropriate data.

**export.json**
1. export.json file is attached.

**Log file**
1. .log file is attached.
[export.json.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9991591/export.json.txt)
[2022-11-11__09_54_58.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/9991594/2022-11-11__09_54_58.log)

**Comment by hknokh** [comment] 2022-11-20 21:06
Hey @ddarmond 
Don't know to say you exactly, but it pretty looks like a nodejs memory issue.
Try to assign more heap to yor process:
https://help.sfdmu.com/faq/troubleshooting/i-have-an-javascript-heap-out-of-memory-error-how-to-resolve
I have no option to test the system with so much records.
Hope it will help you.

**Comment by 0cv** [comment] 2022-11-22 18:38
This could be related to https://github.com/jsforce/jsforce/issues/697, which looks like a 5 (!!) years old issue https://github.com/jsforce/jsforce/issues/697

**Comment by 0cv** [comment] 2022-11-22 18:56
Confirming that this is the issue. I simply pushed up the `highWaterMark` (just for a quick&dirty test) and it queried successfully & then deleted >2m records on an object.

**Comment by hknokh** [comment] 2022-11-24 06:55
So, I understand that this is not related to SFDMU. Closing it for now.
Thanks for the information regarding the jforce.

**Closed by hknokh** 2022-11-24 06:55 UTC
Labels: help wanted, Resolved / Completed

**Comment by 0cv** [comment] 2022-11-25 20:54
> So, I understand that this is not related to SFDMU
Well, it's related that SFDMU is using version 1.9.3 of jsforce. I don't see the usage of PassThrough in the 2.0 branch. It would be worth giving it a try

**Comment by hknokh** [comment] 2022-11-26 15:42
BTW 
For now I can't make using of the more advanced version of jforce than 1.9.3, because of some breaking changes in the newest versions which requires a work on the SFDMU core itself and regression tests.
I put this on my development roadmap.
Thanks.

**Comment by 0cv** [comment] 2022-11-26 15:50
For this issue, it's not relevant at the moment. I checked the 2.0 branch of jsforce and they didn't fix the bug there either ...

**Comment by mattgrimwade** [comment] 2023-08-17 14:29
Sorry to add a question on a closed thread, but I think I'm encountering the same issue. 

Am I right in understanding that due to the issue with jsforce, the sfdmu tool is essentially limited to 1 million records per object (regardless of memory allocated to node)?

**Comment by swapnilmr2** [comment] 2023-09-11 05:40
@0cv  I am also facing similar issue. How did you set up highWaterMark in node js?
 cc : @hknokh

**Comment by 0cv** [comment] 2023-09-15 12:11
> @0cv I am also facing similar issue. How did you set up highWaterMark in node js? cc : @hknokh

I just bumped up the value to something bigger

**Comment by mfabbri** [comment] 2023-11-05 19:05
Hi @0cv, I'm facing the same issue but I don't know where to bump the highWaterMark value: can you help? Thanks

**Comment by 0cv** [comment] 2023-11-09 08:50
> Hi @0cv, I'm facing the same issue but I don't know where to bump the highWaterMark value: can you help? Thanks

@mfabbri simply here https://github.com/jsforce/jsforce/blob/c04515846e91f84affa4eb87a7b2adb1f58bf04d/lib/record-stream.js#L123

**Comment by mfabbri** [comment] 2023-11-09 19:20
sorry @0cv and thank you for pointing me to the jsforce repo. But what should I do after bumping the highWaterMark value there? How can I fix the issue in this repo? Thank you
