### ISSUE TITLE
[QUESTION] - Incase of ORG to ORG migration with Upsert operation, Columns are different in both insert and update csv files.

### ISSUE THREAD

**Issue by kvenkatasivareddy** [forcedotcom/SFDX-Data-Move-Utility#701] opened 2024-03-27 10:04 UTC
Hi Team, 

Firstly i want to thank you guys for your constant improvement and support for the plugin. 

Question:
  Incase of ORG to ORG migration with Upsert operation for an object, we know that 2 csv files will be generated. Even the all the fields were defined as part of SOQL query, why the few columns are not there as part of both insert and update csv files? 
  
Example: I'm trying to migrate Account object along with 2 other objects. I have attached the export.json and the csv files

Export.json:
[export.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14771346/export.txt)

CSV Files: 
[Account_insert_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14771356/Account_insert_target.csv)
[Account_update_target.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14771359/Account_update_target.csv)

Account_insert_target.csv has the below columns:
`a_User_Roles__c, Account_Info__c, Account_Journey__c,  Account_NRR__c,  Account_Region__c, AccountNumber, AccountSource, AnnualRevenue, BillingCity, BillingCountry,  BillingGeocodeAccuracy,  BillingLatitude, BillingLongitude,  BillingPostalCode, BillingState,  BillingStreet, Contract_Start_Date__c,  Converted_from_Lead__c,  Customer_Journey__c, Date_Field_test__c,  Demo_Field__c, dupcheck__dc3DisableDuplicateCheck__c, Fax, Id,  Industry,  Is_Customer__c,  Jigsaw,  MNDA_Fully_Executed_Date__c MNDA_Signed__c , MSA_Date__c, MSA_Signed__c, Name,  Number_of_Contacts__c, Number_of_Pipelines__c,  Number_of_Tools__c,  Number_of_Users__c,  NumberOfEmployees, Phone, Point_of_Contact_Email__c, RecordTypeId,  Referral__c, Referrer__c, ShippingCity,  ShippingCountry, ShippingGeocodeAccuracy, ShippingLatitude,  ShippingLongitude, ShippingPostalCode,  ShippingState, ShippingStreet,  SicDesc Sub_Region__c, Territories__c,  Text_Field__c, Type,  User_Roles__c, Website.`

Account_update_target.csv has the below columns:
`Common_VC__c, Id,  ParentId,  RecordTypeId , Referrer__c, RelatedAccounts__c`

Why the Common_VC__c, ParentId and RelatedAccounts__c columns from update csv file are not as part of insert csv file?

Thanks
Sivareddy

**Comment by hknokh** [comment] 2024-03-31 23:56
I put this  back to "in progress".

**Comment by rajeswaropsera** [comment] 2024-04-05 10:26
Hi, I am also facing the same. Is that an expected behavior

**Comment by hknokh** [comment] 2024-04-10 02:09
Hello,

The file _insert.csv includes fields that are updated or inserted in the target.

Concerning the Id field during insertion: Record Ids are not transferred to the target for insertion. Instead, they are generated once the records have been inserted and are then utilized to populate child lookup fields.

As for the other missing fields, these are lookup fields. 
Since the target parent record Ids are unknown during the insertion phase, it's not possible to populate the child lookups immediately. 
Therefore, SFDMU performs an update on child lookup fields after inserting the parent records.

Best regards

**Comment by hknokh** [comment] 2024-04-10 02:09
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Closed by hknokh** 2024-04-10 02:09 UTC
Labels: help-wanted, in-progress

**Comment by kvenkatasivareddy** [comment] 2024-04-10 03:13
thank you @hknokh :)
