### ISSUE TITLE
Is the application only looking at Profiles for Data Access vs. Permission Sets?

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#318] opened 2021-06-03 16:16 UTC
If we load custom objects and assign a perm set to the default scratch org user with access to those objects the records will not get loaded. We have to assign a profile with access to those objects for the records to load. The problem comes since the default scratch org user is auto assigned the system admin profile which would not have access to these custom objects. While we then assign a perm set with access, doesn't load.

So my question is if this is correct and by design? Since SFDC is trying to move away from profiles we are needing to create profiles only for SFDMU data loads and manually change the default scratch user each time before running SFDMU.

**Comment by hknokh** [comment] 2021-06-08 18:00
Hello, @veaux  

Sounds strange. 

Normally the Plugin does not manage the access or need a special access to the object or fields. It normally requires read/right access both to the SObject and it's fields which should be updated.
It's managed just like by the standard SF DataLoader app, no difference.

I made some tests in my DEV EDITION org with the Standard User having access to TestObject__c via Permission Sets only not with profile (given only **R/E/C** permissions to TestObject__c and account fields, even not need  to give a Modify All permission) and was not able to reproduce, it's working for me w/o issues.

Regarding the scratch org, I have no option to work with scratch orgs so can't check how it working with the Default user as per you having specific issue with it. But I believe however that there are some other reasons blocking the access to the object rather than the Plugin architecture issue.
Ensure anyway whether you gave the **Create** permissions to your object. It's the important permissions to allow Plugin to edit the fields. By the iimplementation the Plugin automatically skips all fields which the running user have no **create** access to them.

**Comment by hknokh** [comment] 2021-06-15 21:12
Hi, @veaux 
We hope, that your issue is already successfully resolved and we are closing the case for the current moment. 
However, do not hesistate to reopen it at any time, if you will need an addtional help.
Thanks.

**Closed by hknokh** 2021-06-15 21:12 UTC
Labels: help wanted
