### ISSUE TITLE
[BUG]-Specified field in the 'query' parameter are being ignored by the plugin

### ISSUE THREAD

**Issue by Kirill-H** [forcedotcom/SFDX-Data-Move-Utility#311] opened 2021-05-19 04:55 UTC
**Describe the bug**
Specified fields in the 'query' string of export.json are being ignored by the plugin.
When providing the following query: SELECT  Id, firstName, lastName FROM Contact
The log file shows a different query as being processed: Query string: SELECT Id, Name  FROM  Contact 

**To Reproduce**
Move data to a sandbox - explicitly specify which fields to take for an object. As an example:
SELECT  Id, firstName, lastName FROM Contact

**Expected behavior**
Contacts to be created in target sandbox and populated with FirstName and LastName

**export.json**
[export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6505921/export.zip)

**Log file**
[2021-05-19__16_44_50.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6505923/2021-05-19__16_44_50.log)

**Comment by hknokh** [comment] 2021-05-23 04:24
Hello @Kirill-H 
The issue is fixed with the patch of v4.4.1
The problem was because firstName, lastName were starting with lower letter in the SOQL so they were internally removed by the Tool. The tool has internal mechanizm to detect and to correct the field and object names in the query string, which feature worked incorrectly in the given case.  Please reinstall and recheck again.

**Comment by hknokh** [comment] 2021-05-23 04:24
***
The case has been closed for the current moment.
Feel free to reopen it if you will have any additional questions or issues.

**Closed by hknokh** 2021-05-23 04:24 UTC
Labels: bug
