### ISSUE TITLE
[QUESTION] - Is there a way to get Salesforce Id of records in the target org?

### ISSUE THREAD

**Issue by akingumusel** [forcedotcom/SFDX-Data-Move-Utility#713] opened 2024-04-25 21:40 UTC
Hello,

When the new records are created/updated in the target org, is there a way to get a mapping of the old Salesforce Ids (source org) and the new Salesforce Ids (target org)? I can see the old Ids in the CSV files along with any errors, but it does not seem to populate the new Ids into the same file.

Thanks
Akin

**Comment by hknokh2** [comment] 2024-04-25 22:26
Hello,

Thank you for reaching out to me. I don't quite understand your issue and need more information to assist you effectively. Could you please provide the following?

The export.json file
Full log files
Examples of the source CSV files you are trying to import/export
*_target and *_source files generated by the tool
Cheers,

**Comment by akingumusel** [comment] 2024-04-25 22:40
Hi @hknokh ,

Thank you for your response.
I am trying to use the tool for org-to-org migration, and I would like to have as the output of old Salesforce Ids (from the source org) and the new Salesforce Ids (from the target org) in the csv file, to update other satellite systems after the migration.

`"createTargetCSVFiles": true,` configuration creates the target CSV files in target folder. Each {object}_{action}_target.csv file has the old Salesforce Ids in **Id** column, and has the Errors column populated if there was an error. But I would also like to have the target **Id**s for each row, like how dataloader works.

I will not be able to share the logs as it contains the data model of the organisation, but please find a masked copy of the exports.json file. 

We also got a security assessment performed, which I would like to share. But since it contains the organisation information, I would not be able to disclose it publicly. Do you want me to send it security@salesforce.com ?

[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/15122805/export.json)

Thanks
Akin

**Comment by hknokh2** [comment] 2024-04-26 02:57
By the implementation, the target csv files should contain the target ids. I guess that issue might be only for insert operation. I need to do additional check for this point.

Regarding security assessment - first, can you please provide more details what is the assessment did you do and what are the results do you want to share?
Commonly,  FYI, the code of conduct and terms of use of the sf open source projects are available publicly, using of it is solely on user' behalf, and if you have any issues or special restrictions, please immediately stop using the sfdmu plugin (or / and gui app) and move to another tool, that complies your security requirements. 

Thanks.

**Comment by akingumusel** [comment] 2024-04-26 10:11
Yes, totally on the same page. We just got a security review done on the package, and it includes some suggestions to maintainers, so was trying to understand the best way to share it. 
I am not treating it as an expectation for you or Salesforce to act on it etc. More like an fyi.

Thanks

**Comment by hknokh2** [comment] 2024-04-26 10:27
Understood. 
If that's the case, security@salesforce.com is not appropriate as it mainly handles serious legal abuses and complaints. 
As the sole maintainer and developer of the SFDMU, the best way to share your findings with me is via my personal developer email: haim.knokh@gmail.com. 
Unfortunately, I cannot share my work email from Salesforce here. 
If your security restrictions permit, please send the information to the provided developer address. 
Kindly note down this address and confirm with me, as I will remove it from here shortly. 
Thank you.

**Comment by akingumusel** [comment] 2024-04-26 10:37
Thank you Haim, feel free to remove it.

**Comment by hknokh** [comment] 2024-04-28 03:39
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Comment by hknokh** [comment] 2024-04-28 04:29
Thank you for the report, Akin.
I'm reopening this case for additional review.

**Comment by hknokh** [comment] 2024-04-28 15:49
@akingumusel,

I've reviewed the issue regarding the target ID. 
Unfortunately, I can't reproduce the issue on my side. 
The files *_insert_target.csv and *_update_target.csv contain the new (target) record IDs, not the old (source) ones, as it appears on your side. Please ensure that you are using the latest version of SFDMU.

**Comment by akingumusel** [comment] 2024-04-28 16:09
Hi @hknokh,
You are actually correct. It seems to be the new (target) id. Maybe it was the old id in simulation mode, but regardless thank you for checking it, and apologies for the wrong report.

I need the old ID and new ID in the same csv though, as data migration means we will need to update the other platforms that store a reference of the old ids. I checked the code, and will probably end up making the change myself in the local code to link as a plugin, but would you take it as a feature-request as well?

Thanks

**Comment by hknokh** [comment] 2024-04-29 20:30
Yes, please open a new feature request as this one is closed as completed.

**Closed by hknokh** 2024-04-29 20:30 UTC
Labels: help-wanted, completed
