### ISSUE TITLE
[QUESTION]- missing parent lookup records were found. See MissingParentRecordsReport.csv file for the details.

### ISSUE THREAD

**Issue by Josecjr** [forcedotcom/SFDX-Data-Move-Utility#320] opened 2021-06-17 19:41 UTC
**Describe the bug**
The prompt asking if I want to continue is not waiting for my input.

**To Reproduce**
Execute the run plugin

**Expected behavior**
the prompt " missing parent lookup records were found. See MissingParentRecordsReport.csv file for the details. 
Command in progress ...... ?
Continue the job (y/n)?
[export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6672832/export.zip)
[2021-06-17__15_17_25.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/6672835/2021-06-17__15_17_25.log)
 [n]:" should wait unltil I input the value

**export.json**
Attach your **export.json** file

**Log file**
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment] 2021-06-22 18:46
Hello, @Josecjr 

It's not a bug. 

To prevent an accidental data damage when any data issue found + to make the job automatically stopped if there is no any human response for the alerts (lets think the person left to take just a cup of coffe but come back after 2 hours :), we implemented the Plugin to wait for the user's response  during 6 secs, then the default response (n) is automatically choosen and the migration stopped.

You can however supress all these alerts and let the job continue even issues occur by putting  
** promptOnMissingParentObjects: false** 

I see, that you really tired to use this property in your export.json, but take in mind, that it's a **GLOBAL** script property and you put it per object, which is mistake, it should not work.

Take it outside the sobject definition into the global script scope as described here:
https://help.sfdmu.com/full-documentation/configuration-and-running/full-exportjson-format

**Comment by Josecjr** [comment] 2021-06-22 19:09
Thanks!

Em ter., 22 de jun. de 2021 2:46 PM, Haim Knokh ***@***.***>
escreveu:

**Comment by hknokh** [comment] 2021-06-23 05:38
Hi,
We hope, that your issue is already successfully resolved and we are closing the case for the current moment. 
However, do not hesistate to reopen it at any time, if you will need an addtional help.
Thanks.

**Closed by hknokh** 2021-06-23 05:38 UTC
Labels: help wanted
