### ISSUE TITLE
Custom field not recognized in WHERE clause. Error field not found.

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#292] opened 2021-04-28 14:50 UTC
In the WHERE clause of an Account query I keep getting `'No such column' fieldName`. The field and access levels are correct and if I remove that field from the WHERE clause, but still keep in SELECT, then SOQL works fine.

`"query": "SELECT Id, RecordTypeId, AccountSource, Description, Name, hdone__AccountCustomerId__c, hdone__CustomerId__c, hdone__ExternalId__c, hdone__Profile_Image__c FROM Account WHERE hdone__AccountCustomerId__c = '04PU0000000Kz4JMAS' LIMIT 100"` This results in error on the hdone__AccountCustomerId__c field not found.

`"query": "SELECT Id, RecordTypeId, AccountSource, Description, Name, hdone__AccountCustomerId__c, hdone__CustomerId__c, hdone__ExternalId__c, hdone__Profile_Image__c FROM Account LIMIT 100"` No error

The only thing I see is that I'm using a single quote in the WHERE clause for the criteria. This also happens for a 2nd field, same thing and also uses single quote. But if I use escape \' I am getting a Malformed Query error

**Comment by veaux** [comment] 2021-04-28 15:10
After some additional testing the problem does not appear to be the quotes but the use of the custom field in the WHERE clause. So maybe this is not a question anymore but a bug. If I use a standard Account field in WHERE, even with single quotes, works fine. When I use a custom field I get the `'No such column'` error

**Comment by hknokh** [comment] 2021-04-29 10:42
Hello @veaux 

I can't reproduce this. 
- Put the same query in the console in both orgs. Do you have the same issue ?
- If it does not help - provide me access to your sandbox where you have this issue with the query.

**Comment by hknokh** [comment] 2021-05-01 19:56
Please give access to haim.knokh@gmail.com

**Comment by hknokh** [comment] 2021-05-05 07:17
***
The case has been closed for the current moment.
Feel free to reopen it if you will have any additional questions or issues.

**Comment by veaux** [comment] 2021-05-24 19:33
The issue here seems to be if "deleteOldData" is on its not recognizing field mapping. This is where we are getting the 'field not found' since it is looking for the original field name. Turning this off seems to remove the error so seems like a bug fix.

**Comment by hknokh** [comment] 2021-05-26 20:46
Hello @veaux 
When the Tool deletes records it uses only Id column which is not mapped. 
I don't think that deleteOldData=true can cause issues when it's used together with the field mapping.

**Comment by veaux** [comment] 2021-05-26 20:58
To clarify the object names are different as well.

**Comment by hknokh** [comment] 2021-05-27 10:17
Ok, I see.
I need to check how the deleteOldData function respects the field mapping.

**Comment by hknokh** [comment] 2021-05-30 11:43
Hello @veaux 
I've fixed the issue of the deleteOldData.
Now it should respect the object mapping on deleting.
Please reinstall and recheck again.

**Comment by hknokh** [comment] 2021-06-08 16:53
Hi,

We hope, that your case is already resolved and you're completely happy with our Plugin. 

We are closing the ticket for the current moment.

However, feel free to reopen it, if you want to add a response or you have any additional questions/ issues in relation to this subject.

Thanks!

**Closed by hknokh** 2021-06-08 16:53 UTC
Labels: help wanted
