### ISSUE TITLE
[BUG]-Incorrectly parsing SOQL query where clause if it contains the token "group"

### ISSUE THREAD

**Issue by dclappert** [forcedotcom/SFDX-Data-Move-Utility#586] opened 2023-04-17 01:06 UTC
**Describe the bug**
Including the token "group" in a SOQL query where clause condition causes the query string to be incorrectly parsed. For example, `SELECT createable_true FROM <Some Object> WHERE <Some Field> = 'Test Group'` will cause the following exception `[ERROR] Execution of the command has aborted due to unexpected error: line 1:45 token recognition error at: ''Test'.`. If you simply remove the token "Group" form the query filter, the job will run successfully.

**To Reproduce**
Execute `sfdx sfdmu:run -s <source org> -u <target org> -p ./repro --simulation` with the following `export.json` (substitute object and field refs accordingly).

```
{
  "promptOnMissingParentObjects": false,
  "objects": [
    {
      "operation": "Readonly",
      "query": "SELECT Id FROM <Some Object> WHERE Name = 'Some Name'",
      "externalId": "<Some Field>",
      "master": true
    },
    {
      "operation": "Upsert",
      "query": "SELECT createable_true FROM <Some Object> WHERE <Some Field> = 'Test Group'",
      "externalId": "<Some Field>",
      "master": false
    }
  ]
}
```

**Expected behavior**
The SOQL query should be parsed successfully.

**export.json**
```
{
  "promptOnMissingParentObjects": false,
  "objects": [
    {
      "operation": "Readonly",
      "query": "SELECT Id FROM csdf__Ad_Server__c",
      "externalId": "csdf__Network_Code__c",
      "master": true
    },
    {
      "operation": "Upsert",
      "query": "SELECT createable_true FROM csdf__Targetable__c WHERE csdf__Type__c = 'Bandwidth Group'",
      "targetRecordsFilter": "csdf__Type__c = 'Bandwidth Group'",
      "externalId": "csdf__Ad_Server_Id__c",
      "master": false
    }
  ]
}
```

**Log file**
```
[01:03:17.256] [ERROR] Execution of the command has aborted due to unexpected error: line 1:45 token recognition error at: ''Bandwidth'.
[01:03:17.263] [ERROR] [STACK TRACE] Error: line 1:45 token recognition error at: ''Bandwidth'
    at SyntaxErrorListener.syntaxError (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/soql-parser-js/dist/index.js:382:15)
    at /home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/ProxyErrorListener.js:37:26
    at Array.forEach (<anonymous>)
    at ProxyErrorListener.syntaxError (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/ProxyErrorListener.js:35:24)
    at SOQLLexer.notifyListeners (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/Lexer.js:264:22)
    at SOQLLexer.nextToken (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/Lexer.js:109:34)
    at CommonTokenStream.fetch (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/BufferedTokenStream.js:142:38)
    at CommonTokenStream.sync (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/BufferedTokenStream.js:128:32)
    at CommonTokenStream.nextTokenOnChannel (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/BufferedTokenStream.js:295:18)
    at CommonTokenStream.adjustSeekIndex (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/CommonTokenStream.js:60:21)
    at CommonTokenStream.consume (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/BufferedTokenStream.js:114:27)
    at SOQLParser.consume (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/Parser.js:415:30)
    at SOQLParser.match (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/antlr4ts/Parser.js:140:18)
    at SOQLParser.comparison_operator (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/soql-parser-js/dist/index.js:8666:30)
    at SOQLParser.field_based_condition (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/soql-parser-js/dist/index.js:9070:22)
    at SOQLParser.simple_condition (/home/node/.npm-packages/lib/node_modules/sfdmu/node_modules/soql-parser-js/dist/index.js:9027:30)
[01:03:17.266] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).
```

**Comment by dclappert** [comment] 2023-04-17 14:26
/workspaces/sfdx-spotifyb2b/data-move-utility-config/Targetables/BandwidthGroup/logs/2023-04-17__01_09_06.log

**Comment by hknokh2** [comment] 2023-04-17 18:42
Hello David,

I have reviewed the log file that you provided, and I am using the latest version of the plugin, which is 4.26.10. 

According to the log file it appears that the issue is occurring at a more advanced stage of the processing, and the stack trace does not provide information about which line in the plugin code caused the execution to crash. SOQL parsing is being performed at many different points in the code.

I have also checked the targetRecordsFilter functionality, and it seems to be working correctly with expressions similar to the one you provided. Unfortunately, I was unable to reproduce the issue without having access to the real data model and records.

I noticed that the plugin complained about the token "Bandwidth" (spelled with single quotes). Additionally, the query to "csdf__Ad_Server__c" is written as "SELECT Id, Name FROM csdf__Ad_Server__c WHERE Name = 'companyx OMS'", and it does not contain an external ID field of "csdf__Network_Code__c". This mostly indicates that the "export.json" file you ran differs from the one that you attached to the ticket.

Perhaps you could try debugging the issue using the steps outlined here: https://help.sfdmu.com/debugging?

Best regards.

**Comment by hknokh** [comment] 2023-05-01 09:07
Hello

I'm  closing this case for now.
Hope your issue has been resolved.

Regards

**Closed by hknokh** 2023-05-01 09:07 UTC
Labels: bug, in-progress
