### ISSUE TITLE
[BUG]-Field Mapping using 2 Different Namespaces Generating Error

### ISSUE THREAD

**Issue by veaux** [forcedotcom/SFDX-Data-Move-Utility#379] opened 2021-11-08 02:48 UTC
**Describe the bug**
Appears Related to #343. Insert using FieldMapping.csv with Source and Target having different namespaces does not appear to be working as expected.

**To Reproduce**
Describe steps to reproduce the behavior.
Json Query of:
`SELECT hdunl__CustomMetadataName__c FROM hdunl__Schedule__c WHERE hdunl__StartDateTime__c >= 2021-10-01T00:00:00Z`"

CSV Similar to attached and below:

ObjectName,FieldName,Target
hdunl__Schedule__c,,prov__provSchedule__c
hdunl__Schedule__c,hdunl__CustomMetadataName__c,prov__CustomMetadataName__c
hdunl__Schedule__c,hdunl__StartDateTime__c,prov__StartDateTime__c

Getting error:
`No such column 'hdunl__StartDateTime__c' on entity 'prov__provSchedule__c'. If you are attempting to use a custom field, be sure to append the '__c'`

**Expected behavior**
Would expect Insert of record selected. Error is referencing the Source namespace for the field and Target for object and not respecting mapping.

**export.json**
Attach your **export.json** file
[FieldMapping.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7493922/FieldMapping.csv)

**Log file**
[2021-11-07__21_42_04.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7493923/2021-11-07__21_42_04.log)
Attach your full **.log** file.

**_target.csv** file.
When you have an issue with failed rows, attach the dump of the **_target.csv** file containing the error messages (at least 1-2 relevant full rows).

**Comment by hknokh** [comment] 2021-11-11 10:23
Hello,
What is the export.json file are you using ?

**Comment by veaux** [comment] 2021-11-14 18:03
[exportjson.txt](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/7534323/exportjson.txt)
t

**Comment by veaux** [comment] 2021-11-30 15:47
This doesn't just seem to be namespace related, it appears to be that there WHERE clause in any SOQL query is doing the mapping early. So the WHERE is using the target field name for the source object, resulting in an error. I'm getting same error today and the objects have the same namespace.

**Comment by hknokh** [comment] 2021-11-30 15:54
You are right. Thanks for the finding. 
I see, that prov__provSchedule__c is for the target sobject.

**Comment by hknokh** [comment] 2021-12-18 23:27
Hello @veaux 

I've investigated your case again. The reason is not what you said before.

According to your log, the Tool failed while deleting the target records, so since it's a query to the target environment, typically it should map 3 things: the sobject name, the selected fields and all the fields from the WHERE clause (hdunl__StartDateTime__c => prov__StartDateTime__c).

Actually, the Tool has correctly mapped the object name hdunl__Schedule__c =>  prov__provSchedule__c, selected fields, but it still has not mapped WHERE hdunl__StartDateTime__c >= 2021-10-01T00:00:00Z => WHERE prov__StartDateTime__c >= 2021-10-01T00:00:00Z
And for the above reason you have this error thrown.

During my check, I run the migration job with similar configuration (mapping + missing datetime field on the target side), but the job was completed successfully.

Below the part of the log file, see that the fields where mapped correctly:

[2021-12-17  21:53:08.958] TARGET
[2021-12-17  21:53:08.959] =============
[2021-12-17  21:53:08.961] {Account} Retrieving the TARGET data from Org (STAGE 2: all records) ...
[2021-12-17  21:53:08.962] {Account} Query string: **SELECT Id, Name, StartDate__c  FROM  Account WHERE StartDate__c >= 2021-10-01T00:00:00Z.**
[2021-12-17  21:53:08.967] {Account} Mapping query string ... The target object: Account. The target query string: **SELECT Id, Name, StartDateTarget__c  FROM  Account WHERE  StartDateTarget__c >= 2021-10-01T00:00:00Z.**

So, unfortunatelly  I was not able to reproduce the issue on my side.

I am closing the ticket for the current moment, feel free to reopen upon needs.

**Closed by hknokh** 2021-12-18 23:27 UTC
Labels: bug

**Comment by veaux** [comment] 2021-12-18 23:31
Not deleting anything, creating.

**Comment by hknokh** [comment] 2021-12-18 23:34
Your issue is while deleting records.

**Comment by hknokh** [comment] 2021-12-18 23:35
BTW you should include all source fields from your field mapping in the query string but hdunl__StartDateTime__c is missing

**Comment by hknokh** [comment] 2021-12-18 23:37
This is your issue:

**[21:42:11.928] DELETING OLD DATA FROM THE TARGET ...**
[21:42:11.929] {hdunl__Schedule__c} Deleting old records from the Target ...
[21:42:11.931] {hdunl__Schedule__c} Mapping query string ... The target object: prov__provSchedule__c. The target query string: SELECT Id  FROM  prov__provSchedule__c WHERE hdunl__StartDateTime__c >= 2021-10-01T00:00:00Z.
[21:42:12.204][ERROR] Execution of the command was ABORTED due to unexpected error: 
FROM prov__provSchedule__c WHERE hdunl__StartDateTime__c >= 2021-10-01T00:00:00Z
                                 ^
ERROR at Row:1:Column:44
No such column 'hdunl__StartDateTime__c' on entity 'prov__provSchedule__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names..
[21:42:12.217] [STACK TRACE] INVALID_FIELD: 
FROM prov__provSchedule__c WHERE hdunl__StartDateTime__c >= 2021-10-01T00:00:00Z

**Comment by hknokh** [comment] 2021-12-18 23:39
But as I said I can't reproduce, It's working for me in any of scenarios (update/delete)
