### ISSUE TITLE
[BUG] RecordsTransform: Updating a text field with lookup id values and non lookup values updates twice with unexpected results

### ISSUE THREAD

**Issue by smercer-liquidframeworks** [forcedotcom/SFDX-Data-Move-Utility#875] opened 2024-09-06 19:14 UTC
**Describe the bug**
I have a text field that I want to populate at the very end of my data move job that is a concatenated string value combined of lookup ids and non-lookup ids.  I am getting strange behavior where the first pass sets the string properly, but the second update pass returns null values for all of my non-lookup values.  

**Background**
My client uses a text field to enforce unique constraints object by making the text field unique.  When they do their data seeding operation, I have built out temporary config change instructions that will allow the seeding to complete successfully.  One of these instructions is to remove the unique constraint before seeding starts, and re-enable after seeding is completed.  I also had to turn off a (bad) old workflow rule that updates that field, since the lookups have to be set using multiple passes in multiple object sets.

**To Reproduce**
1) Create a text field on your object and perform a transformation that concatenates lookup ids along with non lookup fields (such as CurrencyIsoCode or a date field).
2) Turn on change tracking for the text field you want to update.
3) Run in simulation mode and observe expected results in the output.
4) Run in normal mode and observe actual text value updated.  Also observe the change tracking for that field.  You should see two different updates.

I ran this two different ways. The first way was to clear out the text field being updated in a separate object set.  The resulted in a consistently wrong value.  However, when I removed the reset on the text field, running the data seeding operation had this strange flip-flop effect that caused the value to change alternate between the desired result and the wrong one.

Here is a snapshot of my condensed export.json file that demonstrates what I am trying to do.  This version of my config assumes that the record already exists in the target org.  I have a larger config file that takes care of the insertions and updates of the lookup values.

Please let me know if there is an issue in my config or if I need to construct a simple example that includes test objects you can put in your org.

```json
{
    "objectSets": [
        {
            "objects": [
                {
                    "query": "SELECT Id,Name,SobjectType,DeveloperName FROM RecordType",
                    "externalId": "Id"
                },
                {
                    "query": "SELECT Id,Natural_Key__c FROM Unit__c",
                    "externalId": "Natural_Key__c"
                },
                {
                    "query": "SELECT Id,Natural_Key__c FROM Treatment_Facilities__c",
                    "externalId": "Natural_Key__c"
                },
                {
                    "query": "SELECT Id,FX5__Name_Unique__c FROM FX5__Catalog_Item__c",
                    "externalId":"FX5__Name_Unique__c"
                },
                {
                    "operation": "Update",
                    "query": "SELECT Id,FX5__SyncID__c FROM FX5__Override__c",
                    "externalId": "FX5__SyncID__c",
                    "master":true,
                    "beforeUpdateAddons": [
                        {
                            "module" : "core:RecordsTransform",
                            "args" : {
                                "fields" : [
                                    {
                                        "alias": "srcExpDate",
                                        "sourceObject": "FX5__Override__c",
                                        "sourceField":"FX5__Expiration_Date__c",
                                        "includeFields": ["Id","FX5__Expiration_Date__c","FX5__SyncID__c"]
                                    },
                                    {
                                        "alias": "srcEffDate",
                                        "sourceObject": "FX5__Override__c",
                                        "sourceField": "FX5__Effective_Date__c",
                                        "includeFields": ["Id","FX5__Effective_Date__c","FX5__SyncID__c"]
                                    },
                                    {
                                        "alias": "targetRtId",
                                        "sourceObject": "FX5__Override__c",
                                        "sourceField": "RecordTypeId",
                                        "includeFields": ["Id","FX5__SyncID__c","RecordTypeId"]
                                    },
                                    {
                                        "alias": "targetCatItemId",
                                        "sourceObject": "FX5__Override__c",
                                        "sourceField": "FX5__Catalog_Item__c",
                                        "includeFields": ["Id","FX5__SyncID__c","FX5__Catalog_Item__c"]
                                    },
                                    {
                                        "alias": "targetPcUnitId",
                                        "sourceObject": "FX5__Override__c",
                                        "sourceField": "Process_Code_Unit__c",
                                        "includeFields": ["Id","FX5__SyncID__c","Process_Code_Unit__c"]
                                    },
                                    {
                                        "alias": "targetTfId",
                                        "sourceObject": "FX5__Override__c",
                                        "sourceField": "TF__c",
                                        "includeFields": ["Id","FX5__SyncID__c","TF__c"]
                                    },
                                    {
                                        "alias":"targetCurrency",
                                        "sourceObject":"FX5__Override__c",
                                        "sourceField":"CurrencyIsoCode",
                                        "includeFields":["FX5__SyncID__c","CurrencyIsoCode"]
                                    }
                                ],
                                "transformations": [
                                    {
                                        "targetObject": "FX5__Override__c",
                                        "targetField": "Process_Code_Matching_Criteria_Field__c",
                                        "expressions": [
                                            "formula.expDate = ((formula.srcExpDate) ? (new Date(formula.srcExpDate)).toISOString().substr(0,10) : 'NOEXPDATE')",
                                            "formula.effDate = ((formula.srcEffDate) ? (new Date(formula.srcEffDate)).toISOString().substr(0,10) : 'NOEFFDATE')",
                                            "formula.rtId = (formula.targetRtId != null ? formula.targetRtId : '')",
                                            "formula.catItemId = (formula.targetCatItemId != null ? formula.targetCatItemId : '')",
                                            "formula.pcUnitId = (formula.targetPcUnitId != null ? formula.targetPcUnitId : '')",
                                            "formula.tfId = (formula.targetTfId != null ? formula.targetTfId : '')",
                                            "formula.csId = 'csId'",
                                            "formula.processCode = 'processCode'",
                                            "formula.currencyIsoCode = (formula.targetCurrency != null ? formula.targetCurrency : 'CURRENCYFAIL')"
                                        ],
                                        "formula": "formula.rtId + formula.catItemId + formula.pcUnitId + formula.tfId + formula.expDate + formula.effDate + formula.csId + formula.processCode + formula.currencyIsoCode + ''"
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]
}
```

[2024-09-06__13_49_10.log](https://github.com/user-attachments/files/16912094/2024-09-06__13_49_10.log)
[FX5__Override__c.csv](https://github.com/user-attachments/files/16912101/FX5__Override__c.csv)

**Expected behavior**

1) The simulation should yield the same results as the actual run in the target update csv file.
2) The second pass on an actual run should calculate non-lookup values properly. 

**Log file**
Attach your relevant log file. 
Reference: https://help.sfdmu.com/sfdmu-gui-app#logging

**Comment by hknokh** [comment] 2024-09-06 19:37
Hello, @smercer-liquidframeworks

Thank you for reporting a bug.
I will take a look at it as soon as possible and let you know of any updates.

Cheers

**Comment by hknokh2** [comment] 2024-09-09 07:08
Hello,

First, I applied a fix to the core:RecordsTransform add-on to prevent the 'flip-flop effect' you were experiencing, so please update the plugin to the latest version.

Second, I created a new article that explains how to perform a data transformation similar to yours:  
[Populate Text Field with Values Taken from Both Source and Target Orgs](https://help.sfdmu.com/examples/record-transformation#example-6-populate-text-field-with-values-taken-from-both-source-and-target-orgs).

Please pay close attention to the new `valueSource` property, which specifies whether the value should be taken from the data source or data target side. Also, remember to exclude any unwanted fields from the update, as they are included in the `fields` definition as transformation sources.

Note that I can't reproduce or investigate your specific use case and configuration in detail, but I believe this article will help you rebuild your `export.json` to achieve the desired result.

**Comment by smercer-liquidframeworks** [comment] 2024-09-09 19:54
Thank you for making this update so quickly.  I'm working implement your suggestions and retry it with the latest version.

**Comment by smercer-liquidframeworks** [comment] 2024-09-09 20:46
I just confirmed 4.36.0 fixed the 'flip-flop effect" that I was observing.  Thanks again!

**Comment by hknokh** [comment] 2024-09-09 22:21
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Closed by hknokh** 2024-09-09 22:21 UTC
Labels: bug, completed
