### ISSUE TITLE
[BUG]-Previously successful CSV fails to load data

### ISSUE THREAD

**Issue by ChristopherMGlass** [forcedotcom/SFDX-Data-Move-Utility#259] opened 2021-02-05 19:45 UTC
**Describe the bug**
A CSV file that has successfully been used to load data into an org consistently for the last 4 months, no longer loads into an org.

This is noticed as of 3.8.1
I suspect this has to do with lines 242-252 in /modules/components/common_components/sfdx.ts

**To Reproduce**
with the attached object definition, and data csv 
run:  sfdx sfdmu:run -s csvfile 

**Expected behavior**
data should load successfully

[Source-Report-export.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5934850/Source-Report-export.zip)
[MED_Product__c.zip](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/5934835/MED_Product__c.zip)

**Comment by hknokh** [comment] 2021-02-06 17:40
Hello @ChristopherMGlass 
It's not an error in 242-252 as you think.)
I changed the handling of the RecordType object, now you can customize an external id for the RecordType as for all other object types. Moreover you can use combined external ids. By default it is DeveloperName;NamespacePrefix;SobjectType.
The default format of the source CSV has been changed as well.
So to make it working again **you need to recreate from scratch** the source CSV file with the newest version of the Plugin (3.8.1) and then use it to import.
Alternatively, revert your local version back to prior to 3.8.1. But it is not recommended.

**Comment by yippie** [comment] 2021-02-08 12:16
@hknokh that is a pretty massive and breaking change to releasee as a X.X.1 update and then on top of that, not even put it in the release notes!

I would never, ever, expect the CSV format to change in a tiny patch release an I am pretty sure no-one else would either.

We use SFDMU in our CI jobs to dataload test data. The 3.8.1 update broke our CI process completely and we had to stop development to troubleshoot, revert and pin SFDMU to an earlier version because of this change.

**Comment by hknokh** [comment] 2021-02-08 14:32
Hello @yippie 

Ok, my friend, I completely understand your problem. I put this in minor version change, because It is just in beta and need to be checked for the regressions . So, thank you very much for the finding! But, please, don't use a lot of emotions in your messages, because I don't like this kind of communication, let's speak productively instead to resolve this asap.

So, my goal is still to remain with the this imporvement, because it solves me a lot of other issues, but sure I need to make the Plugin accepts the old-fashion csvs also. 

I think (but not checking it deeply), the difference should be only in **RecordType.DeveloperName** column title that has replaced with  **RecordType.$$DeveloperName$NamespacePrefix$SobjectType**.

As a temporary workarround please try to replace the column title and let me know if it is working for you.
From my side I will try to resolve it permanently. 

But also plz keep in mind that I am very overloaded with my primary job. However this issue got a highest priority and I will tackle it now and I will fix it ASAP.

Thank you

**Comment by yippie** [comment] 2021-02-08 14:47
If this is beta, it got released as fully released into the nodejs stream as `sfdx plugins:install sfdmu` was installing this beta version.

I am frustrated because we lost a day of dev time due to this. To be fair, we should be better about version pinning EVERYTHING we install during the CI process so we are definitely partially at fault here also because bugs happen and we should be testing all dependency updates before letting them in to our own streams as well. Will be doing that going forward.

**Comment by hknokh** [comment] 2021-02-08 14:54
@yippie 
Ok. Did you try  to just replace the column name ?

**Comment by ImJohnMDaniel** [comment] 2021-02-08 18:30
My development teams are seeing the same issues as of this morning.  We have reverted back to v3.7.21 and we are stable again.

**Comment by hknokh** [comment] 2021-02-08 18:34
@ImJohnMDaniel 
Are you also trying to load the CSV file created prior the v3.8.1 ?

**Comment by ImJohnMDaniel** [comment] 2021-02-08 18:43
Yes, I have read the entire thread here and can confirm that this is our issue.   I have not tried changing the record type column label yet.  I will get to that.  You can appreciate that when my entire development team was stalled over setup of scratch orgs this morning, it was my top priority to revert them back to a stable version first and triage suggested fixes second. 

I completely echo everything that @yippie has said thus far.  I appreciate that you want to try betas versions and potential changes, but you have to do so slowly, precisely, and with lots of warning _**to your customers**_.  Beta features should be released on a different tag in npm and not on the "released" stream in nodejs as @yippie mentioned.  The cost in productivity to our teams is not something to ignore.  

I will work with our teams to adjust the CSV files and get back up to v3.8.1 as soon as feasible.

**Comment by hknokh** [comment] 2021-02-08 20:25
@ImJohnMDaniel @yippie 

3.8.1 was well tested release, but unfortuanatelly I missed this regression. Although I do my best effort to make this Tool working soomthly for you (and as you know it is pretty stable and well working product), It is a completely volunteering project in my free time to donate to the folk, it's not an official product with full mandatory support, so I can not take the responsibility on possible issues with it and it's completely your choice to use or not to use it with your customers and teems. But really thank you very much for the trust and I'm sorry for the inconvinience caused. 
Also I appreciate your contribution in finding possible bugs to make the Tool better.

Anyway, right now I uploaded to the npm the new patch 3.8.2 that is the same as 3.8.0 (which is before the broken update 3.8.1), that should work with your CSVs. Please update and let me know if all is working fine now.

Thank you!

**Comment by hknokh** [comment] 2021-02-09 20:14
Hello @ChristopherMGlass 
Regarding your issue, I uploaded now the new version 3.9.0 that implements improved handling of the RecordType lookups. However it still does support old CSV source files created with earlier versions of the Plugin.
Please update the plugin, retry and let me know if your files are working good with this update.
FYI @ImJohnMDaniel @yippie

**Comment by hknokh** [comment] 2021-02-11 22:43
I justed updated the Plugin (the latest v3.9.2) with some fixes regarding your issue.

**Comment by hknokh** [comment] 2021-02-13 17:10
Closed this case due to no reponse. Please, let me know if any issue.

**Closed** 2021-02-13 17:10 UTC
Labels: bug, resolved
