### ISSUE TITLE
Can't import to an SF org data generated with master slave setup

### ISSUE THREAD

**Issue by gvpalsson** [forcedotcom/SFDX-Data-Move-Utility#702] opened 2024-03-27 13:14 UTC
**Describe the bug**
We are extracting product data into csv files to be used for import into our SF orgs. To limit the scope of the data we have picked the product2 and price book objects to be the master objects with a filter on curtain product2 records.  The other related objects are set to be slaves so only enough data needed for the relationships with the masters are being selected.

This data is successfully extracted and the amount of data in the csv files all make sense. But when this data is imported into an org we get this error:
[10:30:27.720] [ERROR] Execution of the command has aborted due to unexpected error: Cannot read properties of undefined (reading 'yellow').
[10:30:27.725] [ERROR] [STACK TRACE] TypeError: Cannot read properties of undefined (reading 'yellow')
    at UX.warn (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\node_modules\@salesforce\command\lib\ux.js:203:41)
    at Logger.log (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\components\common_components\logger.js:355:83)
    at MigrationJobTask._apiProgressCallback (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:1363:29)
    at BulkApiV2_0Engine.processCRUDApiBatchAsync (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\components\api_engines\bulkApiV2_0Engine.js:100:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BulkApiV2_0Engine.processCRUDApiJobAsync (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:143:33)
    at async BulkApiV2_0Engine.executeCRUD (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:95:29)
    at async BulkApiV2_0Engine.executeCRUDMultithreaded (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\models\api_models\ApiEngineBase.js:102:20)
    at async ___updateData (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:844:37)
    at async MigrationJobTask.updateRecords (C:\Users\gvpalsson\AppData\Local\sf\node_modules\sfdmu\lib\modules\models\job_models\migrationJobTask.js:670:45)
[10:30:27.730] [ERROR] Execution of the command sfdmu:run has been completed. Exit code 1 (COMMAND_UNEXPECTED_ERROR).

We noticed that the product2 file generated in the source folder for the import has multiple additional records added to the end of it. They do not contain all the required fields which most likely is causing this error.

Adding the parameter "importCSVFilesAsIs": true to the export.json we hoped that this fix of the csv files would not be done and files imported as they are but that run reports not data retrieved from the source so nothing is imported.

**To Reproduce**
Run 
> sf sfdmu:run -s org -u csvfile
to extract the data.

Run 
> sf sfdmu:run -s csvfile -u org
to import csv files to the target org. First with "importCSVFilesAsIs": false to see the error. Then with "importCSVFilesAsIs": true to see that no data is imported to an org.

**Expected behavior**
The product data to be imported successfully to the target org.

**export.json**
[export.json](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14773637/export.json)

**Log file**
Log with the error:
[2024-03-27__10_26_23.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14773647/2024-03-27__10_26_23.log)
Log with no data retrieved from source and imported to org using "importCSVFilesAsIs": true:
[2024-03-27__11_51_13.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14773648/2024-03-27__11_51_13.log)

**_source.csv** file.
Generated during "importCSVFilesAsIs": false
[Product2_source.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14773771/Product2_source.csv)

Generated during "importCSVFilesAsIs": true
[Product2_source.csv](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14773787/Product2_source.csv)

**Comment by hknokh2** [comment] 2024-03-27 13:18
Hello,
Thank you for reaching out to me. 
Indeed it seems to be a bug.
I will take a look on this and let you know if there are any updates.
Cheers.

**Comment by AlwaysThinkin** [comment] 2024-03-28 17:24
Is this affecting all csv2org imports? I've been unable to insert records from Contact.csv even though they are reliably copied to Contact_source.csv with no errors reported, just:

> {Contact} Data retrieval (Source) has been completed. Got 0 new records.

**Comment by hknokh2** [comment] 2024-03-28 18:47
Your issue may be related to a malfunction within the logging engine, potentially triggered by unique conditions specific to your data or environment. Alternatively, it could be a bug in the Salesforce DX (SFDX) CLI that only appears under certain circumstances in your setup. While I'm unable to reproduce this problem directly, I might be able to implement a fix that could potentially resolve the issue.

**Comment by hknokh2** [comment] 2024-03-28 18:48
And it can affect the migration job since the plugin is crashed.

**Comment by AlwaysThinkin** [comment] 2024-03-31 22:27
MacOs Sonoma 14.1, node v21.7.1, salesforce/cli/2.26.10 darwin-arm64 node-v20.10.0

Executing `sf sfdmu run --sourceusername csvfile --targetusername mig1`

against contact.csv (and contact_source.csv is identical)
> Id,FirstName, LastName, Email
> "","328a", "Apple","328a@salesforce.com.invalid"
> "","328b", "BigCar","328b@salesforce.com.invalid"
> "","328c", "BigCar","328c@salesforce.com.invalid"

with export.json
```
{
    "objects": [
        {
            "query": "SELECT Id, FirstName, LastName, Email FROM Contact",
            "externalId":"Id",
            "operation": "Insert"
        }
    ],
    "importCSVFilesAsIs": false
}
```

```
[2024-03-31__18_09_05.log](https://github.com/forcedotcom/SFDX-Data-Move-Utility/files/14817784/2024-03-31__18_09_05.log)
```

**Comment by hknokh** [comment] 2024-03-31 23:54
Hello,

First, I would suggest you to upgrade to the latest:
@salesforce/cli/2.34.7 

Second.
It seems that in your setup, the inclusion of ID values for each record in your source CSV file has been missed. 
If you do not intend to provide record IDs and lookup IDs, it's crucial to enable the `excludeIdsFromCSVFiles` option by setting it to true. 
More details on this configuration can be found at: [Full SFDMU export.json configuration](https://help.sfdmu.com/full-configuration).

For scenarios involving relationships between objects—such as when inserting Contacts and Accounts, where Contact records require the `AccountId` field to be populated—it's necessary to include the appropriate identifiers. For example, in your `Contacts.csv` file, you should include either `AccountId` or `Account.Name` values, presuming that `Name` is used as the external ID for Account records. 
For an illustration of this configuration, refer to: [SFDMU Examples](https://help.sfdmu.com/examples/configuration/csv-import-export).
Take a look on the `AccountBrand.csv` file, which opts for `Account.ExternalID__c` over `AccountId` to associate an AccountBrand record with its parent Account, under the assumption that `ExternalID__c` serves as the external ID for the Account object. 

I recommend applying these adjustments to your source files, as they may address your issue. 
Meanwhile, I will further investigate the specific error related to your existing configuration and inform you if I discover anything.

Best regards.

**Comment by AlwaysThinkin** [comment] 2024-04-01 19:45
Thanks for confirming this but is not my problem - sorry for hijacking the thread!

**Comment by hknokh2** [comment] 2024-04-10 01:52
Hello,

Under normal circumstances, the SFDMU validates source CSV files by analyzing the relationships between them. It attempts to fill in missing IDs and lookup columns to ensure as smooth a data import process as possible.

When importCSVFilesAsIs = true is set, SFDMU bypasses this step of correcting CSV files, treating the source CSVs as if they have already been verified and are correct. Consequently, if the data you're providing is inconsistent, SFDMU may be unable to update the target organization with this data.

Regarding the master/slave configuration: in slave mode, SFDMU can add extra records to child objects as needed to maintain relationships between migrated objects. In master mode, records are imported based solely on the criteria specified by the WHERE clause in the query string.

Best regards,

**Comment by hknokh** [comment] 2024-04-10 01:57
Hello.
 
This case is now considered resolved, and I am closing it for now. If you have any additional questions or concerns, please don't hesitate to reach out.

Regards.

**Closed by hknokh** 2024-04-10 01:57 UTC
Labels: bug, completed, non-reproducible
