### ISSUE TITLE
[APP-BUG]-Didn't understand relationship 'Contact' in field path when selecting fields from Opportunity

### ISSUE THREAD

**Issue by shawnholt** [forcedotcom/SFDX-Data-Move-Utility#323] opened 2021-07-07 01:10 UTC
**Failed to resolve query correctly from the app.  Similar issue (and commented) on #163 **

**See note, include standard fields in gui on opportunity and contact roll**
Describe steps to reproduce the behavior.

**Migration to csv**

**Comment by shawnholt** [comment] 2021-07-07 01:32
The Opportunity object has two contact lookups (one is listed as standard master detail in the GUI) and the a custom field from NPSP (Salesforce non-profit edition). When I remove one of them, the error does not occur.

**Comment by rtoepfer** [comment] 2021-07-09 21:15
I'm receiving this error as well.  I have two lookup fields on the Opportunity to the Contact.  I have the Contact object also pulled in with external id "account.name;full_name__c"

**Comment by hknokh** [comment] 2021-08-02 12:50
Hello @shawnholt, @rtoepfer 

Sorry for the very late reply. I was completely oveloaded all the last weeks ...

Please see my today's response to the case  #163 .

Regarding the GUI issue. The GUI is simply running the Plugin in the background  and showing  the console output. So the issue is coming from the Plugin. But it's not exacly issue as I explained there. 

Unfortunatelly, not all specific cases are handled by the GUI and  sometimes we really need to tweak the export.json produced by the GUI APP manually.
I'm closing the case for now. If you have another question or need help, you are always welcome.

**Closed by hknokh** 2021-08-02 12:50 UTC
Labels: bug
